# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/simon/Desktop/vitadev/new_vita_game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/simon/Desktop/vitadev/new_vita_game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/simon/Desktop/vitadev/new_vita_game/CMakeFiles /Users/simon/Desktop/vitadev/new_vita_game/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/simon/Desktop/vitadev/new_vita_game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named new_vita_game.vpk

# Build rule for target.
new_vita_game.vpk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 new_vita_game.vpk
.PHONY : new_vita_game.vpk

# fast build rule for target.
new_vita_game.vpk/fast:
	$(MAKE) -f CMakeFiles/new_vita_game.vpk.dir/build.make CMakeFiles/new_vita_game.vpk.dir/build
.PHONY : new_vita_game.vpk/fast

#=============================================================================
# Target rules for targets named new_vita_game.self

# Build rule for target.
new_vita_game.self: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 new_vita_game.self
.PHONY : new_vita_game.self

# fast build rule for target.
new_vita_game.self/fast:
	$(MAKE) -f CMakeFiles/new_vita_game.self.dir/build.make CMakeFiles/new_vita_game.self.dir/build
.PHONY : new_vita_game.self/fast

#=============================================================================
# Target rules for targets named new_vita_game

# Build rule for target.
new_vita_game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 new_vita_game
.PHONY : new_vita_game

# fast build rule for target.
new_vita_game/fast:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/build
.PHONY : new_vita_game/fast

src/bgm.obj: src/bgm.c.obj

.PHONY : src/bgm.obj

# target to build an object file
src/bgm.c.obj:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/bgm.c.obj
.PHONY : src/bgm.c.obj

src/bgm.i: src/bgm.c.i

.PHONY : src/bgm.i

# target to preprocess a source file
src/bgm.c.i:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/bgm.c.i
.PHONY : src/bgm.c.i

src/bgm.s: src/bgm.c.s

.PHONY : src/bgm.s

# target to generate assembly for a file
src/bgm.c.s:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/bgm.c.s
.PHONY : src/bgm.c.s

src/controls.obj: src/controls.c.obj

.PHONY : src/controls.obj

# target to build an object file
src/controls.c.obj:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/controls.c.obj
.PHONY : src/controls.c.obj

src/controls.i: src/controls.c.i

.PHONY : src/controls.i

# target to preprocess a source file
src/controls.c.i:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/controls.c.i
.PHONY : src/controls.c.i

src/controls.s: src/controls.c.s

.PHONY : src/controls.s

# target to generate assembly for a file
src/controls.c.s:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/controls.c.s
.PHONY : src/controls.c.s

src/kiss_fft.obj: src/kiss_fft.c.obj

.PHONY : src/kiss_fft.obj

# target to build an object file
src/kiss_fft.c.obj:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/kiss_fft.c.obj
.PHONY : src/kiss_fft.c.obj

src/kiss_fft.i: src/kiss_fft.c.i

.PHONY : src/kiss_fft.i

# target to preprocess a source file
src/kiss_fft.c.i:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/kiss_fft.c.i
.PHONY : src/kiss_fft.c.i

src/kiss_fft.s: src/kiss_fft.c.s

.PHONY : src/kiss_fft.s

# target to generate assembly for a file
src/kiss_fft.c.s:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/kiss_fft.c.s
.PHONY : src/kiss_fft.c.s

src/kiss_fftr.obj: src/kiss_fftr.c.obj

.PHONY : src/kiss_fftr.obj

# target to build an object file
src/kiss_fftr.c.obj:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/kiss_fftr.c.obj
.PHONY : src/kiss_fftr.c.obj

src/kiss_fftr.i: src/kiss_fftr.c.i

.PHONY : src/kiss_fftr.i

# target to preprocess a source file
src/kiss_fftr.c.i:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/kiss_fftr.c.i
.PHONY : src/kiss_fftr.c.i

src/kiss_fftr.s: src/kiss_fftr.c.s

.PHONY : src/kiss_fftr.s

# target to generate assembly for a file
src/kiss_fftr.c.s:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/kiss_fftr.c.s
.PHONY : src/kiss_fftr.c.s

src/main.obj: src/main.c.obj

.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/main.c.s
.PHONY : src/main.c.s

src/objects.obj: src/objects.c.obj

.PHONY : src/objects.obj

# target to build an object file
src/objects.c.obj:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/objects.c.obj
.PHONY : src/objects.c.obj

src/objects.i: src/objects.c.i

.PHONY : src/objects.i

# target to preprocess a source file
src/objects.c.i:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/objects.c.i
.PHONY : src/objects.c.i

src/objects.s: src/objects.c.s

.PHONY : src/objects.s

# target to generate assembly for a file
src/objects.c.s:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/objects.c.s
.PHONY : src/objects.c.s

src/player.obj: src/player.c.obj

.PHONY : src/player.obj

# target to build an object file
src/player.c.obj:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/player.c.obj
.PHONY : src/player.c.obj

src/player.i: src/player.c.i

.PHONY : src/player.i

# target to preprocess a source file
src/player.c.i:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/player.c.i
.PHONY : src/player.c.i

src/player.s: src/player.c.s

.PHONY : src/player.s

# target to generate assembly for a file
src/player.c.s:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/player.c.s
.PHONY : src/player.c.s

src/player_bullet.obj: src/player_bullet.c.obj

.PHONY : src/player_bullet.obj

# target to build an object file
src/player_bullet.c.obj:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/player_bullet.c.obj
.PHONY : src/player_bullet.c.obj

src/player_bullet.i: src/player_bullet.c.i

.PHONY : src/player_bullet.i

# target to preprocess a source file
src/player_bullet.c.i:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/player_bullet.c.i
.PHONY : src/player_bullet.c.i

src/player_bullet.s: src/player_bullet.c.s

.PHONY : src/player_bullet.s

# target to generate assembly for a file
src/player_bullet.c.s:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/player_bullet.c.s
.PHONY : src/player_bullet.c.s

src/verlet.obj: src/verlet.c.obj

.PHONY : src/verlet.obj

# target to build an object file
src/verlet.c.obj:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/verlet.c.obj
.PHONY : src/verlet.c.obj

src/verlet.i: src/verlet.c.i

.PHONY : src/verlet.i

# target to preprocess a source file
src/verlet.c.i:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/verlet.c.i
.PHONY : src/verlet.c.i

src/verlet.s: src/verlet.c.s

.PHONY : src/verlet.s

# target to generate assembly for a file
src/verlet.c.s:
	$(MAKE) -f CMakeFiles/new_vita_game.dir/build.make CMakeFiles/new_vita_game.dir/src/verlet.c.s
.PHONY : src/verlet.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... new_vita_game.vpk"
	@echo "... new_vita_game.self"
	@echo "... new_vita_game"
	@echo "... src/bgm.obj"
	@echo "... src/bgm.i"
	@echo "... src/bgm.s"
	@echo "... src/controls.obj"
	@echo "... src/controls.i"
	@echo "... src/controls.s"
	@echo "... src/kiss_fft.obj"
	@echo "... src/kiss_fft.i"
	@echo "... src/kiss_fft.s"
	@echo "... src/kiss_fftr.obj"
	@echo "... src/kiss_fftr.i"
	@echo "... src/kiss_fftr.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/objects.obj"
	@echo "... src/objects.i"
	@echo "... src/objects.s"
	@echo "... src/player.obj"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/player_bullet.obj"
	@echo "... src/player_bullet.i"
	@echo "... src/player_bullet.s"
	@echo "... src/verlet.obj"
	@echo "... src/verlet.i"
	@echo "... src/verlet.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

